apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-pern-backend:latest
        ports:
        - containerPort: 5000
